[book]
authors = ["George Atkinson", "Audrey Dutcher"]
language = "en"
multilingual = false
src = "src"
title = "vizia-book"

[output.html.playground]
runnable = false

[output.html.fold]
enable = true
level = 0

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]